sudo: false
language: c
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]$/
matrix:
  include:
    - os: linux
      language: python
      python: "2.6"
    - os: linux
      language: python
      python: "2.7"
    - os: linux
      language: python
      python: "3.2"
    - os: linux
      language: python
      python: "3.3"
    - os: linux
      language: python
      python: "3.6"
    - os: linux
      language: python
      python: "pypy-5.3.1"
script:
  - python run.py deps
  - python run.py ci
