version: 2
jobs:
  py26:
    macos:
      # macOS 10.12, last version with Python 2.6
      xcode: 9.2.0
    steps:
      - checkout
      - run: /usr/bin/python2.6 run.py deps
      - run: /usr/bin/python2.6 run.py ci
  pypy:
    macos:
      # macOS 10.14.4
      xcode: 10.3.0
    steps:
      - checkout
      - run: brew install pypy
      - run: pypy run.py deps
      - run: pypy run.py ci
workflows:
  version: 2
  python-26:
    jobs:
      - py26
  python-pypy:
    jobs:
      - pypy
